### ISSUE TITLE
Wrong part numbers sent to KitSpace for 1M resistor

### ISSUE THREAD

**Issue by SteveF161** [ozel/DIY_particle_detector#13]
Hi Oliver

I've started to build the alpha detector and I've hit a problem (No, not soldering the SMD, though that did cause a certain amount of frustration!). I ordered all the parts through KitSpace and Farnell but when my son and I got to R5, it was nowhere to be seen. It's in the KitSpace manifest but, as you can see from the screenshot, the part number seems to be for a 100k resistor.

Steve
![WrongPart](https://user-images.githubusercontent.com/28903476/97084977-59fe6a00-1612-11eb-88cb-7c5442d18194.png)

**Comment by ozel** [comment]
Hi Steve, thanks for pointing this out! I've corrected the part number for R5 at Farnell in the alpha-spectrometer file in 010041b1e182f9f5b558d1ccba435b52a0fc5777.
It should be reflected on Kitspace with the next automatic sync or when @kasbah runs a manual update.
There other order codes for Mouser etc. were correct, I've just updated a few more alternatives according to current parts availability.

Congratulations on soldering the SMD part. I know it's hard for the first time, tweezers and patients definitly go a long way there.
At least you and your son may now have a better feeling how on earth our modern consumer electronics devices can be so small and capabable at the same time. :-)
