### ISSUE TITLE
PROBLEMS WITH THE SCRIPT analyse_and_plot_pulses.py

### ISSUE THREAD

**Issue by josepanglada6** [ozel/DIY_particle_detector#23]
Hi Ozel,
When I copy the script analyse_and_plot_pulses.py and go to SELECT DATASHEET, I put where its requiered the name of the document .msgp. But when I run the terminal (execute) i have this error: FileNotFoundError: [Errno 2] No such file or directory: './data/KCL_9-44g_1x3x3cm_touchingdiodecase_pulses_2019-07-08_23-07-18___947___11-47.pkl' 
What represents that I have to do? Do I have to download also the documents .pkl?
Thanks

**Comment by ozel** [comment]
please use the discussions for questions
