### ISSUE TITLE
Please upload your pictures here for the wiki gallery

### ISSUE THREAD

**Issue by Matthias32** [ozel/DIY_particle_detector#4]
![IMG_5474](https://user-images.githubusercontent.com/26323856/86839219-709fa600-c0a1-11ea-848e-94c4675af830.JPEG)
![IMG_5470](https://user-images.githubusercontent.com/26323856/86839222-71d0d300-c0a1-11ea-912d-722952c6ea9f.JPEG)
![IMG_5478](https://user-images.githubusercontent.com/26323856/86839223-72696980-c0a1-11ea-9b91-ab077a0ccf31.JPEG)
![IMG_5479](https://user-images.githubusercontent.com/26323856/86839227-739a9680-c0a1-11ea-8c79-271bf4ea06d0.JPEG)
![IMG_5477](https://user-images.githubusercontent.com/26323856/86839230-739a9680-c0a1-11ea-83c4-500694a403fa.JPEG)

**Comment by ozel** [comment]
Thanks a bunch, @Matthias32! I've added some to the wiki gallery and will embed the rest as examples for a nice radiation window solution in the other wiki pages.  

I am leaving this issue open so that others will hopefully be encouraged to upload their own build pictures as well! :-)

**Comment by ozel** [comment]
adding Malte's build picture from https://www.mikrocontroller.net/topic/495968#6327455 to make it public
![beta](https://user-images.githubusercontent.com/653212/87235154-15d7b880-c3d9-11ea-987e-3fc4223cff35.jpg)

**Comment by Matthias32** [comment]
![IMG_5773](https://user-images.githubusercontent.com/26323856/93909918-a3505680-fd00-11ea-96ba-a92540f5a23c.JPEG)
Mobile version

**Comment by Matthias32** [comment]
Disassembly of foil capacitors
![IMG_5905](https://user-images.githubusercontent.com/26323856/95664714-b5c4ef80-0b4a-11eb-96ae-a4ff08719d7a.JPEG)
![IMG_5906](https://user-images.githubusercontent.com/26323856/95664718-beb5c100-0b4a-11eb-8a62-5f1702e3101b.JPEG)
![IMG_5902](https://user-images.githubusercontent.com/26323856/95664724-d12ffa80-0b4a-11eb-9f2f-ab6e64e1f599.JPEG)
